keys:
  - &admin_detroyejr age1al3t5f5368nr7yke4deklpuxz2dwr0l5swmvu0raktr3flkjk9jqlwh6ch

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini|sops)$
    key_groups:
      - age:
          - *admin_detroyejr
