-- Plugins need to be loaded first.
require("user.plugins")

require("user.cmp")
require("user.colorscheme")
require("user.comment")
require("user.conform")
require("user.gitsigns")
require("user.keymaps")
require("user.lsp")
require("user.luasnip")
require("user.mini")
require("user.netrw")
require("user.noice")
require("user.options")
require("user.quarto")
require("user.snippets")
require("user.telescope")
require("user.treesitter")
require("user.whichkey")
