-- Plugins need to be loaded first.
require("user.plugins")

require("user.alpha")
require("user.autopairs")
require("user.cmp")
require("user.colorscheme")
require("user.comment")
require("user.gitsigns")
require("user.keymaps")
require("user.lsp")
require("user.luasnip")
require("user.noice")
require("user.options")
require("user.snippets")
require("user.statusline")
require("user.telescope")
require("user.toggleterm")
require("user.treesitter")
require("user.whichkey")
require("user.zenmode")
