#!/usr/bin/env bash
hyprctl activewindow -j | jq --raw-output .title 
socat -u UNIX-CONNECT:/run/user/1000/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | \
  stdbuf -o0 awk -F '>>|,' '/^activewindow>>/{print substr($3, 1, 40) }'
