#!/usr/bin/env bash
spaces (){
  WORKSPACE_WINDOWS=$(hyprctl workspaces -j | jq 'map(select(.windows > 0) | {key: .id | tostring, value: .windows}) | from_entries')
  ACTIVE_WINDOWS=$(hyprctl activeworkspace -j | jq "{(.id | tostring): 1}")
  ALL_WINDOWS=$(echo "[${ACTIVE_WINDOWS}, ${WORKSPACE_WINDOWS}]" | jq 'add')
  seq 1 10 | jq --argjson windows "${ALL_WINDOWS}" --slurp -Mc 'map(tostring) | map({id: ., windows: ($windows[.]//0)})' | jq -Mc 'map(select(.windows > 0))'
}

spaces
socat -u UNIX-CONNECT:/run/user/1000/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
  spaces
done
