#!/usr/bin/env bash

sudo nixos-rebuild switch --flake $HOME/.config/dotfiles#${1} && \
  pkill eww && \
  pkill hyprpaper && \
  hyprctl dispatch exec hyprpaper && \
  sleep 1 && \
  hyprctl dispatch exec eww open bar && \
  hyprctl reload && \

  # Nightfox caches a compiled version of theme which needs to be removed if you 
  # want nix to manage your neovim theme dynamically.
  rm -rf $HOME/.cache/nvim
