#!/usr/bin/env bash
selected=`cat $HOME/.local/bin/bash/.tmux-cht-languages $HOME/.local/bin/bash/.tmux-cht-command | fzf`
if [[ -z $selected ]]; then
    exit 0
fi

read -p "Enter Query: " query

if grep -qs "$selected" $HOME/.local/bin/bash/.tmux-cht-languages; then
    query=`echo $query | tr ' ' '+'`
    tmux new bash -c "echo \"curl cht.sh/$selected/$query/\" & curl cht.sh/$selected/$query & while [ : ]; do sleep 1; done"
else
    tmux new bash -c "curl -s cht.sh/$selected~$query | less"
fi
