#!/usr/bin/env bash

tmux new-session -d -s "tools"
tmux new-window -t "tools" -n btop -c $HOME/.config/dotfiles/
tmux send-keys -t "tools:2" 'btop' Enter
# tmux new-window -t "tools" -n notes -c $HOME/.config/dotfiles/
# tmux new-window -t "tools" -n tiny -c $HOME/.config/dotfiles/
# tmux send-keys -t "tools:4" 'tiny' Enter
tmux attach -t "tools:1"

